# Generated by Django 2.0.13 on 2019-11-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('code_user', models.CharField(max_length=15)),
                ('active', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=5)),
                ('cpf', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=10)),
            ],
        ),
    ]
